/**
 * Kagi API
 * The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it\'s not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you\'ve made with our APIs! 
 *
 * OpenAPI spec version: 1
 * Contact: support@kagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchRequestExtract } from '../models/SearchRequestExtract';
import { SearchRequestFilters } from '../models/SearchRequestFilters';
import { SearchRequestLens } from '../models/SearchRequestLens';
import { SearchRequestPersonalizations } from '../models/SearchRequestPersonalizations';
import { HttpFile } from '../http/http';

/**
* Used to upload the search query
*/
export class SearchRequest {
    /**
    * Search query to run.
    */
    'query': string;
    /**
    * Type of results to return.
    */
    'workflow'?: SearchRequestWorkflowEnum;
    /**
    * **(EXPERIMENTAL)** Format to serialize the API response as. The exact contents and structure of markdown output is still being worked on - please send your feedback!
    */
    'format'?: SearchRequestFormatEnum;
    /**
    * Lens to apply to the search. Can be a built-in lens\'s identifier or a lens ID as shown on https://kagi.com/settings/lenses when a lens is set to be shareable. Can be just the ID portion of the URL (`https://kagi.com/lenses/ID`) or the full URL.
    */
    'lensId'?: string;
    'lens'?: SearchRequestLens;
    /**
    * Number of seconds to allow for collecting search results. Lower values will return results more quickly, but may be lower quality or inconsistent between calls. If omitted, will use the latest recommended value by Kagi.
    */
    'timeout'?: number;
    /**
    * Page number for paginated results. Must be between 1 and 10.
    */
    'page'?: number;
    /**
    * Maximum number of results to return. Must be between 1 and 1024.  **NOTE:** This does not change the amount of results requested, it only limits the maximum amount returned. If omitted, the API always gives you the most results we can get in a single pass. 
    */
    'limit'?: number;
    'filters'?: SearchRequestFilters;
    'extract'?: SearchRequestExtract;
    /**
    * Whether safe search is enabled, omitting potentially NSFW content.
    */
    'safeSearch'?: boolean;
    'personalizations'?: SearchRequestPersonalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflow",
            "baseName": "workflow",
            "type": "SearchRequestWorkflowEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "SearchRequestFormatEnum",
            "format": ""
        },
        {
            "name": "lensId",
            "baseName": "lens_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lens",
            "baseName": "lens",
            "type": "SearchRequestLens",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "SearchRequestFilters",
            "format": ""
        },
        {
            "name": "extract",
            "baseName": "extract",
            "type": "SearchRequestExtract",
            "format": ""
        },
        {
            "name": "safeSearch",
            "baseName": "safe_search",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "personalizations",
            "baseName": "personalizations",
            "type": "SearchRequestPersonalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SearchRequestWorkflowEnum {
    Search = 'search',
    Images = 'images',
    Videos = 'videos',
    News = 'news',
    Podcasts = 'podcasts'
}
export enum SearchRequestFormatEnum {
    Json = 'json',
    Markdown = 'markdown'
}

