/**
 * Kagi API
 * The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it\'s not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you\'ve made with our APIs! 
 *
 * OpenAPI spec version: 1
 * Contact: support@kagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchResult } from '../models/SearchResult';
import { HttpFile } from '../http/http';

/**
* Holds all the search results for the query specified. As results have different types and sources, they are separated into different fields within this object. For example image results are stored under `data.image` while news results are stored under `data.news`. All results will have the same main structure, but additional data might be stored under the `data.{name}[].props` path. Please look at each different type of result for more information about this.
*/
export class Search200ResponseData {
    /**
    * Contains all search results for html pages or websites.
    */
    'search'?: Array<SearchResult>;
    /**
    * Contains all search results for images.
    */
    'image'?: Array<SearchResult>;
    /**
    * Contains all search results for videos.
    */
    'video'?: Array<SearchResult>;
    /**
    * Contains all search results for podcasts.
    */
    'podcast'?: Array<SearchResult>;
    /**
    * Contains all search results for creators of podcasts.
    */
    'podcastCreator'?: Array<SearchResult>;
    /**
    * Contains all search results for news articles.
    */
    'news'?: Array<SearchResult>;
    /**
    * Contains results that are obtained by searching for slightly different queries. These questions are stored under the `props.question` path.
    */
    'adjacentQuestion'?: Array<SearchResult>;
    /**
    * If the search query was a math equation, or unit conversions, things that can be answered quickly, the result will be in here.
    */
    'directAnswer'?: Array<SearchResult>;
    /**
    * Contains news results from publishers collected and stored in Kagi\'s news index.
    */
    'interestingNews'?: Array<SearchResult>;
    /**
    * Contains small web results from publishers collected and stored in Kagi\'s small web index.
    */
    'interestingFinds'?: Array<SearchResult>;
    /**
    * Contains detailed summary and tabulated information about a person, place, or thing.
    */
    'infobox'?: Array<SearchResult>;
    /**
    * Contains all search results that link to code resources or repositories.
    */
    'code'?: Array<SearchResult>;
    /**
    * If the search query was a package tracking number, the correct package tracking website should be present in this collection.
    */
    'packageTracking'?: Array<SearchResult>;
    /**
    * Contains all search results for public records, such as government documents or public court records.
    */
    'publicRecords'?: Array<SearchResult>;
    /**
    * Contains all search results for the current weather.
    */
    'weather'?: Array<SearchResult>;
    /**
    * Contains a list of searches that are related to the current search, and may help narrow down the results.
    */
    'relatedSearch'?: Array<SearchResult>;
    /**
    * Contains all search results that are lists of things. Results with titles like \"5 things you didn\'t know about...\", or \"10 of the best headphones\".
    */
    'listicle'?: Array<SearchResult>;
    /**
    * Contains all search results for archived websites that may not be available anymore
    */
    'webArchive'?: Array<SearchResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "search",
            "baseName": "search",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "podcast",
            "baseName": "podcast",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "podcastCreator",
            "baseName": "podcast_creator",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "news",
            "baseName": "news",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "adjacentQuestion",
            "baseName": "adjacent_question",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "directAnswer",
            "baseName": "direct_answer",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "interestingNews",
            "baseName": "interesting_news",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "interestingFinds",
            "baseName": "interesting_finds",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "infobox",
            "baseName": "infobox",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "packageTracking",
            "baseName": "package_tracking",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "publicRecords",
            "baseName": "public_records",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "weather",
            "baseName": "weather",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "relatedSearch",
            "baseName": "related_search",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "listicle",
            "baseName": "listicle",
            "type": "Array<SearchResult>",
            "format": ""
        },
        {
            "name": "webArchive",
            "baseName": "web_archive",
            "type": "Array<SearchResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Search200ResponseData.attributeTypeMap;
    }

    public constructor() {
    }
}
